import type { Metadata } from "next";

import "./globals.css";
import { AuthProvider } from './contex/loginContext';



export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <AuthProvider>
      <body
        
      >
        {children}
       
      </body>
      </AuthProvider>
    </html>
  );
}
